# Generated by Django 6.0.2 on 2026-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_added_relatedname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(verbose_name=255),
        ),
    ]
