# Generated by Django 6.0.2 on 2026-03-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipe_created_on_recipe_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ledger.profile'),
        ),
    ]
